### ISSUE TITLE
No instructions on use

### ISSUE THREAD

**Issue by RyRy79261** [Aniket-Engg/sol-profiler-vscode#1]
There is no indication how to execute this extension.

**Comment by Aniket-Engg** [comment]
GIF image is explaining it. If it is not sufficient, i will add text explanations. Thanks for the feedback.

**Comment by Aniket-Engg** [comment]
[Instructions](https://github.com/Aniket-Engg/sol-profiler-vscode/blob/master/README.md#how-to-use) added. Hope they are helpful.

**Comment by Aniket-Engg** [comment]
Reopen if required!
