### ISSUE TITLE
Does not support importing external libraries when using workspaces (like in yarn and lerna)

### ISSUE THREAD

**Issue by alesanro** [Aniket-Engg/sol-profiler-vscode#17]
In case of having several workspaces with packages and smart contracts imported libraries are searched only inside this package node_modules but probably should also have a shot on looking for upper-level node_modules like npm/yarn module resolution do.

**Comment by Aniket-Engg** [comment]
Hi @alesanro , Thanks for raising this. Can you please add steps to reproduce it? That will be really helpful

**Comment by alesanro** [comment]
So basically I have the next project structure:

![Screen Shot 2019-06-14 at 12 08 52 PM](https://user-images.githubusercontent.com/2529842/59498007-36afa080-8e9d-11e9-93bb-ff8a51067366.png)

where 
- `TokenAirdrop` -> `contracts`, TokenAirdrop -> `utils` are workspaces in terms of lerna
```json
{
  "packages": [
    "contracts/*",
    "hunter-airdrop/*",
    "utils/*"
  ],
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true
}
```

- Workspaces contain their packages, like `actions-tracking`, `actions-tracking-artifacts`, etc.
- `actions-tracking` is a package with smart contracts

Running `yarn` (link `npm install`) in workspaced environment installs equal dependencies from all packages in the root `node_modules` (some of them could have different version requirements so they will be installed locally in a package).
![Screen Shot 2019-06-14 at 12 08 52 PM](https://user-images.githubusercontent.com/2529842/59498767-b8ec9480-8e9e-11e9-9736-cdc7895752db.png)

- in `ActionsTracking` contract there is the next code
```solidity
pragma solidity ^0.4.24;

import "openzeppelin-solidity/contracts/access/roles/SignerRole.sol";
```
and sol-profiler tries only at `~/Documents/TokenAirdrop/contracts/actions-tracking/node_modules/openzeppelin-solidity/contracts/access/roles/SignerRole.sol`.

-------
It is expected that it could search like module resolution do: beginning from local `node_modules` and the going on the next level `../node_modules`, `../../node_modules` and so on.

**Comment by Aniket-Engg** [comment]
@alesanro  I got your point. Actually contract with import is flattened using the package [sol-straightener](https://www.npmjs.com/package/sol-straightener). To determine the path of node_modules folder, it uses default way suggested by npm using [npm root](https://docs.npmjs.com/cli/root.html).

Although it should work properly in this case too but I am not sure how we can incorporate the required changes.

**Comment by alesanro** [comment]
@Aniket-Engg Hi, I've made [MR](https://github.com/Aniket-Engg/sol-straightener/pull/18) for `sol-straighterer`. I suppose that will resolve the issue and will allow to go through several node_modules folders, not only a single parent.

**Comment by Aniket-Engg** [comment]
That's great. I will review and merge it.
